version: 2

models:
    - name: stg_products
      description: "This dataset includes data about the products sold by Olist"
      columns:
          - name: product_pk
            description: "unique product identifier"
            tests:
                - unique
                - not_null
          - name: product_category_name
            description: "root category of product, in Portuguese"
          - name : product_name_lenght
            description: "number of characters extracted from the product name"
          - name : product_description_lenght
            description: "number of characters extracted from the product description"
          - name : product_photos_qty
            description : "number of product published photos"
          - name : product_weight_g
            description : "product weight measured in grams"
          - name : product_length_cm
            description : "product length measured in centimeters"
          - name : product_height_cm
            description : "product height measured in centimeters"
          - name : product_width_cm
            description : "product width in centimeters"

    - name: stg_orders
      description: "A table with all orders and its primary key."
      columns:
          - name: order_pk
            description: "unique identifier of the order"
            tests:
                - unique
                - not_null
          - name : customer_fk
            description : "key to the customer dataset. Each order has a unique customer_id"
            tests : 
                - not_null
          - name : order_status
            description : Reference to the order status. This is simplified.
          - name : order_purchase_date
            description : "Shows the purchase timestamp"
          - name : order_approved_date
            description : "Shows the payment approval timestamp"
          - name : order_delivered_carrier_date
            description : "Shows the order posting timestamp. When it was handled to the logistic partner"
          - name : order_delivered_customer_date
            description : "Shows the actual order delivery date to the customer"
          - name : order_estimated_delivery_date
            description : "Shows the estimated delivery date that was informed to customer at the purchase moment"
          - name : est_delivery_delay
            description : "the difference between the estimated and actual delivery dates in days"

    - name: stg_order_items
      description: "This dataset includes data about the items purchased within each order"
      columns:
          - name: order_item_uiid
            description: "order item unique identifier. Combines order id and item id"
            tests:
                - not_null
          - name: order_fk
            description: "order unique identifier"
            tests:
                - not_null
          - name: order_item_id
            description: "sequential number identifying number of items included in the same order"
            tests:
                - not_null
          - name: product_fk
            description: "product unique identifier"
            tests:
                - not_null
          - name: seller_fk
            description: "seller unique identifier"
            tests:
                - not_null
          - name : shipping_limit_date
            description : "Shows the seller shipping limit date for handling the order over to the logistic partner"
          - name : price
            description : "item price"
          - name : freight_value
            description  : "item freight value item (if an order has more than one item the freight value is splitted between items)"

    - name : stg_payments
      description: "This dataset includes data about the orders payment options"
      columns:
          - name: order_fk
            description : "unique identifier of an order"
            tests:
                - not_null
          - name: numb_payment_methods
            description : "a customer may pay an order with more than one payment method. If he does so, a sequence will be created to"
          - name : payment_type
            description : "method of payment chosen by the customer"
          - name : payment_installments
            description : "number of installments chosen by the customer"
          - name : payment_value
            description : "transaction value"

    - name : stg_customers
      description: "This dataset has information about the customer and its location. We can use it to identify unique customers in the orders dataset and to find the orders delivery location"
      columns:
          - name: customer_fk
            description: "key to the orders dataset. Each order has a unique customer_id"
            tests:
                - not_null
                - unique
          - name : customer_uiid
            description: " unique identifier of a customer."
            tests:
                - not_null
          - name : customer_city
            description: "customer city name"
          - name : customer_state
            description: "customer state"
    - name : stg_reviews
      description : "This dataset includes data about the reviews made by the customers."
      columns : 
            - name : review_pk
              description : "This is the primary key, unique review identifier"
              tests:
                - not_null
                - unique
            - name : order_fk
              description : " unique order identifier"
              tests:
                - not_null
            - name : review_score
              description : "Note ranging from 1 to 5 given by the customer on a satisfaction survey."

